ColibriAssetAccounting/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

import web.views as views


urlpatterns = [
    path('', views.MainView.as_view(), name='dashboard'),
    path('assets', views.AssetList.as_view(), name='assets'),
    path('auth', views.Auth.as_view(), name='auth'),
    path('logout', views.LogOut.as_view(), name='logout'),
    path('profile', views.Profile.as_view(), name='profile'),
    path('search', views.Search.as_view(), name='search'),
    path('assets/<int:pk>', views.AssetDetail.as_view(), name='assets_detail'),
    path('assets/<int:pk>/add-image', views.CreateAssertImage.as_view(), name='create_asset_image'),
    path('assets/<int:pk>/remove-image', views.DeleteAssertImage.as_view(), name='delete_asset_image'),
    path('assets/<int:pk>/clone', views.CloneAssert.as_view(), name='clone_asset'),
    path('assets/create', views.CreateAssert.as_view(), name='create_asset'),
    path('assets/update/<int:pk>', views.UpdateAsset.as_view(), name='update_asset'),
    path('assets/delete/<int:pk>', views.DeleteAssert.as_view(), name='delete_asset'),
    path('locations', views.LocationList.as_view(), name='locations'),
    path('locations/<int:pk>', views.LocationDetail.as_view(), name='locations_detail'),
    path('locations/create', views.CreateLocation.as_view(), name='create_location'),
    path('locations/update/<int:pk>', views.UpdateLocation.as_view(), name='update_location'),
    path('locations/delete/<int:pk>', views.DeleteLocation.as_view(), name='delete_location'),
    path('orders', views.OrderList.as_view(), name='orders'),
    path('orders/create', views.CreateOrder.as_view(), name='create_order'),
    path('orders/create', views.CreateOrder.as_view(), name='create_order'),
    path('import', views.AssetsImport.as_view(), name='assets_import'),
    path('notifications', views.NotificationsListView.as_view(), name='notifications')
]

web/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Location(models.Model):
    """ Точки / склады
    """
    name = models.CharField(max_length=256, verbose_name='Название')
    city = models.CharField(max_length=256, verbose_name='Город', blank=True, null=True)
    address = models.CharField(max_length=256, verbose_name='Адрес', blank=True, null=True)
    phone = models.CharField(max_length=32, verbose_name="Номер телефона", blank=True, null=True)
    description = models.TextField(verbose_name="Описание", blank=True, null=True)

    def assets_count(self) -> int:
        count = 0
        for asset in self.assets.all():
            count += asset.count
        return count

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Адрес"
        verbose_name_plural = "Адреса"


class CustomUser(AbstractUser):
    """ Расширенная модель пользователя
    """
    locations = models.ManyToManyField(
        Location,
        verbose_name="Местоположение",
        related_name='users',
        blank=True,
    )


class Asset(models.Model):
    """ Активы
    """
    STATUS_CHOICES = ("in_work", "broken", "under_repair", "in_reserve")
    STATUS_CHOICES_RUS = ("В работе", "Сломано", "В ремонте", "В запасе")
    STATUS_CHOICES = list(zip(STATUS_CHOICES, STATUS_CHOICES_RUS))

    STATE_CHOICES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))

    name = models.CharField(max_length=256, verbose_name='Наименование')
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        verbose_name="Местоположение",
        related_name='assets',
        blank=True,
        null=True
    )
    year_of_purchase = models.DateField(verbose_name="Дата покупки")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата и время обновления")
    price = models.DecimalField(verbose_name="Стоимость", decimal_places=2, max_digits=7, blank=True, null=True)
    state = models.IntegerField(verbose_name="Состояние", choices=STATE_CHOICES)
    status = models.CharField(max_length=256, verbose_name='Статус', choices=STATUS_CHOICES)
    is_active = models.BooleanField(default=True, verbose_name="Активный")
    auto_update_price = models.BooleanField(default=False, verbose_name="Автообновление стоимости")
    ozon_slug = models.CharField(max_length=256, verbose_name="Ссылка на ozon", blank=True, null=True)
    count = models.PositiveIntegerField(verbose_name="Количество")
    parent = models.ForeignKey(
        "Asset",
        on_delete=models.SET_NULL,
        verbose_name="Родительский актив",
        related_name="children_list",
        blank=True,
        null=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актив"
        verbose_name_plural = "Активы"


class AssetImage(models.Model):
    """ Изображения к активу
    """
    title = models.CharField(max_length=256, verbose_name='Описание', blank=True, null=True)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, verbose_name="Актив", related_name="images")
    image = models.ImageField(upload_to="images/assets/", verbose_name="Изображенеие")
    # created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки")

    def __str__(self):
        return f"{self.asset.name}" if not self.title else f"{self.asset.name} - {self.title}"

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения"


class Order(models.Model):
    """ Отчеты
    """
    file_path = models.CharField(max_length=256, verbose_name="Путь к файлу отчета", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")

    def __str__(self):
        return f"{self.created_at}"

    def get_file_name(self):
        file_name = None if not self.file_path else self.file_path.split('/')[-1]
        return file_name

    class Meta:
        verbose_name = "Отчет"
        verbose_name_plural = "Отчеты"


class History(models.Model):
    """ История
    """
    STATUS_CHOICES = ("in_work", "broken", "under_repair", "in_reserve")
    STATUS_CHOICES_RUS = ("В работе", "Сломано", "В ремонте", "В запасе")
    STATUS_CHOICES = list(zip(STATUS_CHOICES, STATUS_CHOICES_RUS))

    STATE_CHOICES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5))

    event_name = models.TextField(verbose_name='Наименование события')
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE, verbose_name="Актив", related_name="history")
    old_name = models.CharField(
        max_length=256, verbose_name='Старое название', choices=STATUS_CHOICES, blank=True, null=True
    )
    new_name = models.CharField(
        max_length=256, verbose_name='Новое название', choices=STATUS_CHOICES, blank=True, null=True
    )
    old_location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        verbose_name="Местоположение",
        blank=True,
        null=True,
        related_name='old_history'
    )
    new_location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        verbose_name="Местоположение",
        blank=True,
        null=True,
        related_name='new_history'
    )
    old_price = models.DecimalField(
        verbose_name="Старая стоимость", decimal_places=2, max_digits=7, blank=True, null=True
    )
    new_price = models.DecimalField(
        verbose_name="Новая стоимость", decimal_places=2, max_digits=7, blank=True, null=True
    )
    old_state = models.IntegerField(verbose_name="Старое состояние", choices=STATE_CHOICES, blank=True, null=True)
    new_state = models.IntegerField(verbose_name="Новое состояние", choices=STATE_CHOICES, blank=True, null=True)
    old_status = models.CharField(
        max_length=256, verbose_name='Старый татус', choices=STATUS_CHOICES, blank=True, null=True
    )
    new_status = models.CharField(
        max_length=256, verbose_name='Новый статус', choices=STATUS_CHOICES, blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время создания записи")

    def __str__(self):
        return f"{self.created_at} - {self.asset.name}"

    class Meta:
        verbose_name = "История"
        verbose_name_plural = "История"


class Notifications(models.Model):
    """ Модель уведомлений """
    LEVEL_CHOICES = ("success", "error", "warning", "info", "debug")
    LEVEL_CHOICES_RUS = ("Успешно", "Ошибка", "Предупреждение", "Информация", "Отладка")
    LEVEL_CHOICES = list(zip(LEVEL_CHOICES, LEVEL_CHOICES_RUS))

    message = models.TextField(verbose_name="Сообщение")
    level = models.CharField(max_length=256, verbose_name='Статус', choices=LEVEL_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время сообщения")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="Пользователь")

    def __str__(self):
        return f"{self.message}"

    class Meta:
        verbose_name = "Уведомление"
        verbose_name_plural = "Уведомления"

templates/web/asset_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-heading">
        <div class="row">
            <div class="col-md-4">
                <h1 class="page-title">{{ asset.name }}</h1>
            </div>
            <div class="col-md-2">
                <a type="button" href="/assets/{{ asset.pk }}/add-image"
                   class="btn btn-outline-primary px-5 mt-5 float-right">
                    Загрузить изображение
                </a>
            </div>
            <div class="col-md-2">
                <a type="button" href="/assets/update/{{ asset.pk }}"
                   class="btn btn-outline-primary px-5 mt-5 float-right">
                    Редактировать
                </a>
            </div>
            <div class="col-md-2">
                <a type="button" href="/assets/{{ asset.pk }}/clone"
                   class="btn btn-outline-primary px-5 mt-5 float-right">
                    Дублировать
                </a>
            </div>
            <div class="col-md-2">
                <a type="button" href="/assets/delete/{{ asset.pk }}"
                   class="btn btn-outline-danger px-5 mt-5 float-right">
                    Удалить актив
                </a>
            </div>
        </div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'dashboard' %}">Главная</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'assets' %}">Активы</a>
            </li>
            <li class="breadcrumb-item">{{ asset.name }}</li>
        </ol>
    </div>
    <div class="page-content fade-in-up">
        <div class="ibox invoice">
            <div class="invoice-header">
                <div class="row">
                    <div class="col-6">
                        <div>
                            <div class="m-b-5 font-bold">Описание актива</div>
                            <div>
                                <p>{{ asset.description }}</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 text-right">
                        <div class="clf" style="margin-bottom:30px;">
                            <dl class="row pull-right" style="width:450px;">
                                <dt class="col-sm-6">Дата закупки</dt>
                                <dd class="col-sm-6">{{ asset.year_of_purchase }}</dd>
                                <dt class="col-sm-6">Дата регистрации</dt>
                                <dd class="col-sm-6">{{ asset.created_at }}</dd>
                                <dt class="col-sm-6">Дата обновления</dt>
                                <dd class="col-sm-6">{{ asset.updated_at }}</dd>
                            </dl>
                        </div>
                        <div>
                            <div class="m-b-5 font-bold">Местоположение</div>
                            {% if asset.location %}
                                <div>{{ asset.location.name }}</div>
                                <ul class="list-unstyled m-t-10">
                                    {% if asset.location.city %}
                                        <li class="m-b-5">г. {{ asset.location.city }}</li>
                                    {% endif %}
                                    <li class="m-b-5">{{ asset.location.address }}</li>
                                    <li>{{ asset.location.phone }}</li>
                                </ul>
                            {% else %}
                                <p>Не указано</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-striped no-margin table-invoice">
                <tbody>
                {% if asset.parent %}
                    <tr>
                        <td>Родительский актив</td>
                        <td>
                            <a href="/assets/{{ asset.parent.pk }}">{{ asset.parent }}</a>
                        </td>
                    </tr>
                {% endif %}
                <tr>
                    <td>Стасус</td>
                    <td>{{ asset.get_status_display }}</td>
                </tr>
                <tr>
                    <td>Состояние</td>
                    <td>{{ asset.get_state_display }}</td>
                </tr>
                <tr>
                    <td>Стоимость</td>
                    <td>{{ asset.price }}</td>
                </tr>
                <tr>
                    <td>Количество</td>
                    <td>{{ asset.count }}</td>
                </tr>
                <tr>
                    <td>Ссылка на товар</td>
                    <td>
                        {% if 'http' in asset.ozon_slug  %}
                            <a href="{{ asset.ozon_slug }}">{{ asset.ozon_slug }}</a>
                        {% else %}
                            <a href="https://{{ asset.ozon_slug }}">{{ asset.ozon_slug }}</a>
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="mt-5">
                <h4 class="mb-4">Дочерние активы</h4>
                <table class="table table-striped table-bordered table-hover"
                       id="example-table"
                       cellspacing="0"
                       width="100%">
                    <thead>
                    <tr>
                        <th>Наименование</th>
                        <th>Местоположение</th>
                        <th>Стоимость</th>
                        <th>Год закупки</th>
                        <th>Статус</th>
                        <th>Состояние</th>
                        <th>Количество</th>
                    </tr>
                    </thead>
                    {% if asset.children_list.all|length > 15 %}
                        <tfoot>
                        <tr>
                            <th>Наименование</th>
                            <th>Местоположение</th>
                            <th>Стоимость</th>
                            <th>Год закупки</th>
                            <th>Статус</th>
                            <th>Состояние</th>
                            <th>Количество</th>
                        </tr>
                        </tfoot>
                    {% endif %}
                    <tbody>
                    {% include 'inc/childrenRows.html' %}
                    </tbody>
                </table>
            </div>
            {% if asset.images.all|length > 0 %}
                <div id="carouselExampleControls" class="carousel slide mt-5" data-ride="carousel">
                <div class="carousel-inner">
                    {% for photo in asset.images.all %}
                        {% if photo == asset.images.all|first %}
                            <div class="carousel-item active">
                        {% else %}
                            <div class="carousel-item">
                        {% endif %}
                    <img src="{{ photo.image.url }}" class="d-block w-100" alt="{{ photo.title }}" style="max-height: 400px">
                    </div>
                    {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls"
                            data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Предыдущий</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-target="#carouselExampleControls"
                            data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Следующий</span>
                    </button>
                </div>
            </div>
            {% endif %}
            {% if asset.history.all|length > 0 %}
                <h2 class="mb-4 mt-4">История актива</h2>
                <table class="table table-striped no-margin table-invoice mb-5">
                    <tbody>
                    <tr>
                        <th>Дата изменения</th>
                        <th>Событие</th>
                        <th>Старое значение</th>
                        <th>Новое значение</th>
                    </tr>
                    {% for item in asset.history.all %}
                        <tr>
                            <td>{{ item.created_at }}</td>
                            <td>{{ item.event_name }}</td>
                            {% if item.event_name == 'Создание актива' %}<td></td><td></td>{% endif %}
                            {% if item.old_name %}<td>{{ item.old_name }}</td>{% endif %}
                            {% if item.new_name %}<td>{{ item.new_name }}</td>{% endif %}
                            {% if item.old_location %}<td>{{ item.old_location.name }}</td>{% endif %}
                            {% if item.new_location %}<td>{{ item.new_location.name }}</td>{% endif %}
                            {% if item.old_price %}<td>{{ item.old_price }}</td>{% endif %}
                            {% if item.new_price %}<td>{{ item.new_price }}</td>{% endif %}
                            {% if item.old_state %}<td>{{ item.old_state }}</td>{% endif %}
                            {% if item.new_state %}<td>{{ item.new_state }}</td>{% endif %}
                            {% if item.old_status %}<td>{{ item.get_old_status_display }}</td>{% endif %}
                            {% if item.new_status %}<td>{{ item.get_new_status_display }}</td>{% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <style>
                .invoice {
                    padding: 20px
                }

                .invoice-header {
                    margin-bottom: 50px
                }

                .table-invoice tr td:last-child {
                    text-align: right;
                }
            </style>
        </div>
{% endblock %}

templates/web/assets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <div class="row">
                <div class="col-md-8">
                    <h1 class="page-title">Активы</h1>
                </div>
                <div class="col-md-2">
                    <a type="button" href="{% url 'assets_import' %}"
                       class="btn btn-outline-primary px-5 mt-5 float-right">
                        Импорт активов
                    </a>
                </div>
                <div class="col-md-2">
                    <a type="button" href="{% url 'create_asset' %}"
                       class="btn btn-outline-primary px-5 mt-5 float-right">
                        Добавить актив
                    </a>
                </div>
            </div>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">Активы</li>
            </ol>
            <div class="row mx-1 my-0">
                <a type="button" href="/assets"
                   class="btn btn-primary px-5 mt-5 mx-1" style="float: right;">
                    Все
                </a>
                {% for location in locations %}
                    <a type="button" href="/assets?location={{ location.pk }}"
                       class="btn btn-primary px-5 mt-5 mx-1" style="float: right;">
                        {{ location.name }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    {% include 'inc/asset_table.html' %}
                    {% include 'inc/pagination.html' %}
                </div>
            </div>
        </div>
    </div>
    <style>
        tr[class^="child-"] {
            display: none;
        }

        .width30 {
            width: 30px;
        }
    </style>
    <script src="{% static 'js/assetButtonsMixin.js' %}" type="text/javascript"></script>
{% endblock %}

templates/web/create_asset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <h1 class="page-title">Добавление нового актива</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'assets' %}">Активы</a>
                </li>
                <li class="breadcrumb-item">Добавление нового актива</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    <form method="POST">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button class="btn btn-info btn-block mt-5 mb-3" type="submit">Добавить актив</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/web/create_asset_image.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <h1 class="page-title">Добавление изображения актива {{ asset.name }}</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'assets' %}">Активы</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="/assets/{{ asset.pk }}">{{ asset.name }}</a>
                </li>
                <li class="breadcrumb-item">Добавление изображения актива {{ asset.name }}</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    <form method="POST" enctype="multipart/form-data">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button class="btn btn-info btn-block mt-5 mb-3" type="submit">Добавить изображение</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/web/delete_asset.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <h1 class="page-title">Удаление актива {{ asset.name }}</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'assets' %}">Активы</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="/assets/{{ asset.pk }}">{{ asset.name }}</a>
                </li>
                <li class="breadcrumb-item">Удаление актива {{ asset.name }}</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    <p class="mt-4">
                        Актив <b>"{{ asset.name }}"</b> будет удален безвозвратно. Пожалуйста подтвердите действие
                        нажав кнопку ниже.
                    </p>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger btn-block mt-5 mb-3" type="submit">Удалить актив</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/web/delete_location.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <h1 class="page-title">Удаление склада {{ location.name }}</h1>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'locations' %}">Склады</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="/locations/{{ locations.pk }}">{{ location.name }}</a>
                </li>
                <li class="breadcrumb-item">Удаление склада {{ location.name }}</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    <p class="mt-4">
                        Склад <b>"{{ location.name }}"</b> будет удален безвозвратно. Пожалуйста подтвердите действие
                        нажав кнопку ниже.
                    </p>
                    <form method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger btn-block mt-5 mb-3" type="submit">Удалить склад</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/web/locations.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="page-title">Склады</h1>
                </div>
                <div class="col-md-2">
                    {% if user.is_superuser %}
                        <a type="button" href="{% url 'create_location' %}"
                           class="btn btn-outline-primary px-5 mt-5 float-right">
                            Добавить склад
                        </a>
                    {% endif %}
                </div>
            </div>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">Склады</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="ibox">
                <div class="ibox-body">
                    {% include 'inc/location_table.html' %}
                    {% include 'inc/pagination.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/web/notifications.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-content fade-in-up">
        <div class="page-heading">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="page-title">Уведомления</h1>
                </div>
            </div>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'dashboard' %}">Главная</a>
                </li>
                <li class="breadcrumb-item">Уведомления</li>
            </ol>
        </div>
        <div class="page-content fade-in-up">
            <div class="row">
                <div class="col-md-12">
                    <div class="ibox">
                        <div class="ibox-body" style="">
                            {% for item in notifications %}
                                {% if item.level == 'success' %}
                                    <div class="alert alert-success">
                                        <strong>{{ item.get_level_display }}! {{ item.created_at }} - </strong>
                                        {{ item.message }}
                                    </div>
                                {% elif item.level == 'error' %}
                                    <div class="alert alert-danger">
                                        <strong>{{ item.get_level_display }}! {{ item.created_at }} - </strong>
                                        {{ item.message }}
                                    </div>
                                {% elif item.level == 'warning' %}
                                    <div class="alert alert-warning">
                                        <strong>{{ item.get_level_display }}! {{ item.created_at }} - </strong>
                                        {{ item.message }}
                                    </div>
                                {% else %}
                                    <div class="alert alert-info">
                                        <strong>{{ item.get_level_display }}! {{ item.created_at }}</strong>
                                        {{ item.message }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% include 'inc/pagination.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}